### ISSUE TITLE
FR: Allow capturing viewport only

### ISSUE THREAD

**Issue by Gitoffthelawn** [M-Reimer/savescreenshot#1]
Add menuitem in dropdown to capture the viewport only.

**Comment by M-Reimer** [comment]
Do you really think that someone needs this? That would be pretty similar to just using the screenshot option offered by the operating system which works well for capturing the current window.

**Comment by Gitoffthelawn** [comment]
I use it all the time with my current (non web-extension) extension. :)

 It's much faster than using the OS key combination, copying it into another app, and then saving it from  that external app.

**Comment by M-Reimer** [comment]
Fixed with https://github.com/M-Reimer/savescreenshot/commit/c2371551f7219f1e2e1cc2df5ae4558267d70bc8
