### ISSUE TITLE
letzen Speicherpfad merken

### ISSUE THREAD

**Issue by immerDieseRegistrierungen** [M-Reimer/savescreenshot#11]
Sehr geehrter Herr Reimer,

ist es möglich, dass der zuletzt verwendete Speicherort (im Dialog "Speichern unter") bei erneuter Verwendung des Addons verwendet wird und nicht immer das Downloadverzeichnis ausgewählt ist.

Danke und Gruß

**Comment by M-Reimer** [comment]
Es gibt in den Addon-Optionen mehrere "Speichermethoden".

Wenn hier "Dialog Speichern unter..." gewählt ist, dann ist nur Speichern direkt ins Downloadverzeichnis möglich. Das ist eine Einschränkung der Schnittstellen von Mozilla.

Wird stattdessen die erste Option ("Anbieten, die Bilddatei direkt zu öffnen") gewählt, dann kommt zwar eine weitere Rückfrage (ob direkt geöffnet werden soll) aber das hier gewählte Verzeichnis sollte gemerkt werden.

**Comment by M-Reimer** [comment]
Ich mache hier erstmal zu. Wenn noch Fragen sind, dann gerne melden.
Was mit den verfügbaren Schnittstellen im Firefox möglich ist, habe ich aber bereits ausgereizt.
