### ISSUE TITLE
Shortcut to start the plugin

### ISSUE THREAD

**Issue by petrdj** [M-Reimer/savescreenshot#13]
Hello guys, thanks for this plugin, I like it a LOT! :-)

Could you add option to allow Firefox to set the shortcut?

Thank you!

**Comment by M-Reimer** [comment]
What does "set shortcut" mean?

**Comment by M-Reimer** [comment]
Found it. Didn't know that Mozilla has already implemented this.

**Comment by M-Reimer** [comment]
Change is on GIT.
Still needs a lot of testing but it should work.
Also contains a "Reset" button to reset shortcuts.

**Comment by M-Reimer** [comment]
Fixed in 4.0.0

**Comment by orleanski** [comment]
@M-Reimer Thank you for the very useful extension, and I am sorry for bringing the closed issue back alive, 
but how can I take a screenshot with keyboard shortcut alone? seems like I overlooked something.
