### ISSUE TITLE
Request feature: add a notification when directly saving screenshot without prompting

### ISSUE THREAD

**Issue by syldub69** [M-Reimer/savescreenshot#14]
Hi Manuel,
First of all, thanks for your very good extension!
I would like to request this feature: could you add an option to display an optional notification when using the "Directly save to Downloads directory without prompting" option? 
This will allow us to quickly know that the screenshot has been taken. In the current case, we always have to see in the Downloads folder if the screenshot has well been taken. Or sometimes I click many times on the button because I wasn't sure it has been clicked, and as a result I get many screenshots that I have to delete.

**Comment by M-Reimer** [comment]
Currently I don't see any reason why this shouldn't be enabled all the time, so I won't add an option for now.
I can still add an option if someone requests it for some good reason.

**Comment by syldub69** [comment]
I think there is a misunderstanding... If this could be enabled all the time, this is even better! 
For now, there is no notification... that is what I request ;o)

**Comment by M-Reimer** [comment]
Fixed in version 5.1.0

**Comment by syldub69** [comment]
Thanks a lot!
