### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by keith-hall** [M-Reimer/savescreenshot#15]
Hi,

I just wanted to drop a quick note here to say thank you for this great extension - I love it's simplicity, that it does one thing well and doesn't contain any useless bloat like uploading screenshots to various online image providers :+1:

I used to use the "Nimbus Capture" extension, which, while well-made, does suffer from bloat and isn't open source so I could never see how it works or tweak it ;)

Sorry for polluting your issues list with this non-issue, but figured maintainers so rarely get a "thank you" (especially without a "but [x doesn't work etc]") that I hope you won't mind :) (my expectations are that you will close this issue when you have read it, your time is precious so please don't feel obligated to reply :smile: )

Best regards,
Keith

**Comment by M-Reimer** [comment]
Thank you for your nice feedback here and on AMO.

Always nice to get positive feedback from users. For most of the time the only "feedback" are rising user numbers.

In fact my "Save Screenshot" Addon started pretty small. One click to save screenshot of the full page. That's it.

It's my users and their feedback that made "Save Screenshot" to what it is today. Now we have several ways to save the screenshot including copy to clipboard and support for keyboard shortcuts (in case you haven't found them: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox )
