### ISSUE TITLE
getting content from the clipboard and adding it to the file name

### ISSUE THREAD

**Issue by hazephase** [M-Reimer/savescreenshot#16]
hi, 

 I wanted a feature that would add the clipboard content to the file name. I have done some of it my self but I want to know if if sounds interesting to you.

**Comment by M-Reimer** [comment]
New features should always have more than one possible user.
And adding contents from the clipboard to the filename seems like this is a bit too special.
Can you explain why you need this?
You know that you can configure "Save Screenshot" to display a "Save As" dialog which makes it easy for you to paste contents into the filename?

**Comment by hazephase** [comment]
I do about 1400 web screenshots a month, and it would save me some time of that is in the clipboard is already pasted in the file name. 

I know about the "Save As" dialog, but this if I could save time it would be better. I have the code for it also. 

`setInterval( function(){
  navigator.clipboard.readText().then(function (textFromClipboard) {
    //do stuff with textFromClipboard
     copy = textFromClipboard;
  });}, 500);`

I think this has to go into the contentscript.js file

**Comment by M-Reimer** [comment]
Adding something from the clipboard is too random.
What if you copied a 3 pages word document before creating a screenshot?

But this doesn't mean we shouldn't find some improvement for your use case.

Can you explain in detail how you create screenshots? How does the string, you want to add, get into the clipboard?

**Comment by hazephase** [comment]
so what I do some part of the name already set, so lets say like 

> WordPress %h Jan20 

> 
At the end of this string, I want to add the keyWord that I copied from the article that I am trying to clip.

**Comment by M-Reimer** [comment]
What kind of keyword is this. Is there a chance to auto detect it?

**Comment by hazephase** [comment]
the KeyWords change from but I can give you a list and if they find the keyword then they can use it. 

To start with if it can just take the last clipboard that it should work.

**Comment by M-Reimer** [comment]
Taking something from the keyboard renders the whole idea useless for most users. You never **really** know what you copied last. And you forget that "Save Screenshot" can copy to the clipboard, too which will overwrite your copied string.

That's why I don't think that this is a good idea at all. You can't really know what you have in your clipboard. Maybe you copied a 10 page Word document before taking a screenshot without remembering. What to do then? Most operating systems won't even allow you that long file names!

So about the clipboard thing: A definitive NO.

What I'm currently trying to do is to find some alternative way that could be useful for more than exactly one special use case. If we can find something "cool" which may help at least 5% of the user base, then I would be happy to add this.

**Comment by M-Reimer** [comment]
No more feedback for over one week so I'll close this for now. Feel free to reopen if you are still interested in a solution.

I would still be interested in finding an alternative solution for your problem, but for this I would need to know your use case and would have to know what exactly is the task you want to solve.

**Comment by hazephase** [comment]
Sorry for not replying 

So the string I want to add will have a **Keyword**  website name **month and date** **last copied text**. 

There is a group of 6 of us that need this feature.

**Comment by M-Reimer** [comment]
I don't know what you mean with "keyword" but month/date is already possible.

And "copied text" is nothing that I want to have in there. That's why I asked where you got this text from. Is it copied from the website?

**Comment by hazephase** [comment]
ok, then no problem. It still is the best screenshot extension there is.

**Comment by M-Reimer** [comment]
A solution which may useful for more people who want some custom string/tag in their filenames would be the following:

As soon as "%tag" is in the filename pattern, a save attempt pops up a small window where this tag can be entered and is remembered as soon as it is entered. I would remember this even across browser sessions.

So for your "clipboard thing" this would just require you to "Ctrl + V" once into this dialog. At the second screenshot, the tag is already in there and you just have to either click "OK" or press "Enter" on your keyboard.

Would this help for your usecase?
