### ISSUE TITLE
Place selecting PNG/JPG in options

### ISSUE THREAD

**Issue by Gitoffthelawn** [M-Reimer/savescreenshot#2]
Changing between PNG and JPG is a less common action.  I suggest placing it in a separate options UI instead of the dropdown.

**Comment by M-Reimer** [comment]
My plan was to create an option GUI anyway as I want to make the JPEG quality customizable.
I'm still unsure if it is a good idea to place the selection there...
But at least in my opinion it is no good idea to use JPEG at all. It is a much better idea to use PNG and compress the image in an external image manipulation program which offers preview while setting the quality. Only in this way it is possible to see how low the quality can be set for this particular image.

**Comment by Gitoffthelawn** [comment]
Yes, PNG is much better for screenshots, as it has lossless compression.

**Comment by M-Reimer** [comment]
Fixed with https://github.com/M-Reimer/savescreenshot/commit/c2371551f7219f1e2e1cc2df5ae4558267d70bc8
