### ISSUE TITLE
How to setup "Full page (PNG)" as default without any further click?

### ISSUE THREAD

**Issue by pstein** [M-Reimer/savescreenshot#20]
As I found out the newest version of Save Screenshot opens a sub menu/drop down when I click on the SS toolbar icon.

The user is forced to select the desired kind of snapshot.

Since I always use "Full page (PNG)" I want to define this as default.
So in future no further sub menu/drop down should appear but the full page should immediately be printed into *.png file.
Like in previous versions of Save Screenshot AddOn

How can I achieve this?

If this is currently not possible: Can this option be added in the next release?

Thank you 
Peter

**Comment by M-Reimer** [comment]
Have a look at the screenshots and the Add-on settings. If you disable options in the settings, the menus change. If you only leave one combination active, the menu disappears. It always was like this but I changed the default for new installs so users see what could be possible and are somewhat forced to visit the Add-on settings if they want to customize the menu.

**Comment by pstein** [comment]
Ok, it works
Thank you
