### ISSUE TITLE
How to print a whole GooglePhoto WebAlbum webpage?

### ISSUE THREAD

**Issue by pstein** [M-Reimer/savescreenshot#21]
Lets take at first an example:

https://photos.google.com/share/AF1QipPyOz-CUZbDPvjvYG6r-Ntaq_adxqe7cyhMo-quS-rw95UHhstzwcuwVksuGqUiwg?key=d3JIajUwdGtPZ0xWWEFzUzBmUFFFbjdSeGR3eG53

If I try to print this full album webpage with Save Screenshot (in Firefox 78) then it prints only the currently visible part.

There is not auto-scroll down and capturing of all photos.

Why?

Can you make it capturing really the whole webpage?

Thank you
Peter

**Comment by M-Reimer** [comment]
Actually you've found a pretty hard example here where whole page screenshots will fail with almost every screenshot add-on.

What scrolls here is not the page itself but seems to be a <div> inside the page. This is a) difficult to find and if found b) even if scrolled it would be difficult to fit the parts together after screenshotting them.

To create screenshots from such pages it would require a special Add-on to do so. One Add-on per problematic website as it is just way too complex to dig into such pages to manipulate them into a way to make them behave nice for screenshots. And if someone manages to do this Google will break this with the next website update.

That's all not on topic for my small screenshot add-on which has the main target to not need scrolling at all.
