### ISSUE TITLE
Firefox reports "PageInfo: Invalid value for property 'url'" when save method is "Offer to open the image file directly"

### ISSUE THREAD

**Issue by sim-d** [M-Reimer/savescreenshot#22]
Cool tool!

I did notice an error displayed in my Firefox (68) browser console in some cases, however.
When savescreenshot's save method is set to "Offer to open the image file directly" and at least when I screenshot a full page of any significant length, I get the error message:

> PageInfo: Invalid value for property 'url': "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABPoAAAlJCAYAAAAx8w23AAAgAElEQVR4nOzdd3hTV6Lv/fPH+973L+4p99x7zmVanGFCJplkMpm0mUlyJslkJj2Tkz6ZCSRAAsSAwdiADZhiiqkJEHrvYHoLHWK6KTbdFIMrLrJsY1uWZJXf+4ci2bJlyQbbksX38zzreUB7a+21l7Yk75/W3uufBAAAAAAAAKDd+6dgNwAAAAAAAADA3SPoAwAAAAAAAMIAQR8AAAAAAAAQBgj6AAAAAAAAgDBA0AcAAAAAAACEAYI+AAAAAAAAIAwQ9AEAAAAAAABhgKAPAAAAAAAACAMEfQAAAAAAAEAYIOgDAAAAAAAAwgBBHwAAAAAAABAGCPoAAAAAAACAMEDQBwAAAAAAAIQBgj4AAAAAAAAgDBD0AQAAAAAAAGGAoA8AAAAAAAAIAwR9AAAAAAAAQBgg6AMAAAAAAADCAEEfAAAAAAAAEAYI+tCuORxOmarNKiuvUEGhQbl5hbqZnU+hUCgUCoVCoTQouXmFKig0qKy8QqZqsxwOZ7D/nAUAoEUR9KFdqqwyqajYqJvZ+SoqNqqsvEJmi1XWmppgNw0AAAAhylpTI7PFqrLyCq+/JSurTMFuGgAALYKgD+1KWXmF55dY/iADAADA3aqsMnmuDCkrrwh2cwAAuCsEfWgXzBarcvMKVVRslM1uD3ZzAAAAEGZsdruKio3KzSuU2WINdnMAALgjBH0IecbScuXwBxcAAADagNliVU5eoYyl5cFuCgAAzUbQh5DlcDiVf6tYhpIybpQMAACANuNwOFVUbFT+rWL+DgUAtCsEfQhJ1poa5d8q1u2KqmA3BQAAAPeosvIK5d8qZsI3ACEnx2jXZ4vK9FSiQR2jCymtWJ5KNOizRWXKMbaP24gR9CHkuEfyMdkGAAAAg… PlacesUtils.jsm:874
>     validateItemProperties resource://gre/modules/PlacesUtils.jsm:874
>     validatePageInfo resource://gre/modules/PlacesUtils.jsm:1281
>     update resource://gre/modules/History.jsm:723
>     update self-hosted:1009
>     setMetadata resource://gre/modules/DownloadHistory.jsm:310
>     InterpretGeneratorResume self-hosted:1291
>     AsyncFunctionNext self-hosted:840

The screenshot happens with no other problem, the image file is saved, but that error message appears in those instances, and I'm not sure what other effects that error hints at.

The error doesn't appear when I try to screenshot a full page of some short pages (like google.com), but even a google search results page results in that error.

The error doesn't appear when either of the other 2 save methods are selected.

I'm not sure if this is an issue that would only affect Firefox. I don't know much about Firefox, but the "PlacesUtils.jsm" might be referencing the places.sqlite DB that Firefox has?

**Comment by M-Reimer** [comment]
> I'm not sure if this is an issue that would only affect Firefox.

My Add-on only works on Firefox.

> I don't know much about Firefox, but the "PlacesUtils.jsm" might be referencing the places.sqlite DB that Firefox has?

Yes, seems like that. The error does not come from my Add-on directly but from deep within the Firefox backend and my guess is that the error happens if a too big URL (the image is stored in an URL) is requested to be stored in the browsing history.

For all the other save methods I do not use the data:-URL directly. I'll have a look at this. Maybe it is possible to get rid of the data:-URL for "Offer to open the image file directly", too.
