### ISSUE TITLE
Unable to take a snapshot for this webpage

### ISSUE THREAD

**Issue by clsven** [M-Reimer/savescreenshot#23]
The snapshot WebExt works fine for almost all webpages except the following:

https://support.mozilla.org/en-US/kb/what-mozilla-maintenance-service

When I try it I get an error

"Failed to take screenshot"

I am using 64bit Firefox v80.0.1 under 64bit Windows 7

Can you fix it?

Claudia

**Comment by M-Reimer** [comment]
Most Mozilla pages are blacklisted by Mozilla. This means that Add-ons can't access them for security reasons. But I'll check if this page is on this list.

**Comment by M-Reimer** [comment]
Had a look at the blacklist and "support.mozilla.org" is on there. So no way to access any content in this website.
You can make it work by removing "support.mozilla.org" from the extensions.webextensions.restrictedDomains preference but that's kind of risky as it allows **any** Add-on to access it and I think it is on there for a reason.
