### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by ubone** [M-Reimer/savescreenshot#24]
In recent FF versions there was a change to their new screenshot thing again. Now it saves images with 100% zoom - not as you see them (which was true before). I just tried your addon and I see the same so this must be a FF thing. My question is, can you do anything about it?

**Comment by ubone** [comment]
The old `:screenshot` (from dev console) still saves images as you see them.

**Comment by M-Reimer** [comment]
It is a fixed API which I can't influence that much.
But Mozilla is reworking their Screenshot stuff at the moment. I don't know how far they are but their API rework forces me to do some rework anyway. Maybe this will fix this problem. We'll see...

**Comment by M-Reimer** [comment]
Can not reproduce any issues after updating to the new screenshot API.

If the error still exists with the upcoming version 8.0.0, then please open a new Issue with more detailed instructions on how to reproduce.
