### ISSUE TITLE
Feature: pngquant

### ISSUE THREAD

**Issue by ubone** [M-Reimer/savescreenshot#25]
Would you consider adding [pngquant](https://pngquant.org/) support to your addon? It's perfect for images of text.
They're transparent and 3x smaller in size than the rgb png.

**Comment by M-Reimer** [comment]
Seems to be possible but I have to try how slow this runs for bigger screenshots. If this takes too long, then it would be better if you use pngquant externally and it makes no sense to integrate it.

**Comment by M-Reimer** [comment]
Here you can try on your own:
https://psych0der.github.io/pngquantjs/
For me it took pretty long just to fail after some time with big screenshots (long scroll area). It works for small images but takes way longer than a natively compiled version running on the host operating system.
