### ISSUE TITLE
Floating elements

### ISSUE THREAD

**Issue by FranklinYu** [M-Reimer/savescreenshot#29]
Some web pages have floating elements either at the top or at the bottom. Ideally, elements floating at the top of my screen should be also at the top of the screenshot, so it’s simulating a very high screen with the same width. Current behavior is that the element will be at the middle of the screenshot, unless I scroll to the top before taking the screenshot.

**Comment by M-Reimer** [comment]
This is expected behavior. Screenshots represent what you see on your screen. If you want a page screenshot of the page scrolled all the way up, you have to scroll up manually, first.
