### ISSUE TITLE
Page-specific File Names

### ISSUE THREAD

**Issue by jscher2000** [M-Reimer/savescreenshot#3]
Creating file names is no fun! Could you consider something along these lines:

Where you currently have this line in the content script:

```javascript
a.download = "saved_page." + request.suffix;
```

I would prefer the page title (with the URL as a fallback if it's blank), and a date/time stamp. Maybe:

```javascript
var t = document.title.trim();
if (t && t.length > 0){
  t = t.replace(/[^a-z0-9_\-\(\)\{\}\[\]\u00C0-\u01FF]/gi, '_').replace(/_{2,}/g, '_').replace(/_$/,'');
}
if (!t || t.length === 0){
  t = location.hostname + location.pathname;
  t = t.replace(/[^a-z0-9_\-\(\)\{\}\[\]\u00C0-\u01FF]/gi, '_').replace(/_{2,}/g, '_').replace(/_$/,'');
}
var d=new Date(); 
d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); 
var dt = d.toISOString(); 
dt = dt.substr(0, dt.indexOf(".")).replace(/[\-:]/gi, '');
a.download = t + '_' + dt + '.' + request.suffix;
```

Perhaps that's too much for some people, but it's easier to edit a proposed file name than to type it in the first place.

**Comment by M-Reimer** [comment]
I've added something, inspired by what Firefox does when using "Ctrl + S" for saving pages.
My code is much simpler than what Mozilla uses and maybe even a bit more strict when deleting characters.
https://github.com/M-Reimer/savescreenshot/commit/1929932a5019b626de80bf8e3e69b4538dbfb9fe

**Comment by jscher2000** [comment]
Just got the update. Thank you!
