### ISSUE TITLE
Original URL is lost after it is sanitized

### ISSUE THREAD

**Issue by cwfoo** [M-Reimer/savescreenshot#30]
I like to use `%u` in the filename format, but the way this plugin "sanitizes" the URLs makes it difficult or even impossible to recover the original URL from the filename.

If the filename is `httpsgithub.comM-Reimersavescreenshotissuesnew.png`, it is somewhat easy to guess the original URL, but for some other URLs, it is not obvious where I should place the forward slashes. Perhaps this plugin should preserve the entire URL by using [percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding), or at least provide an option for the user to choose percent-encoding.

https://github.com/M-Reimer/savescreenshot/blob/2697adbf2bea8f769866e6d9f40f9bbcde25b342/contentscript.js#L206-L218

**Comment by M-Reimer** [comment]
I don't want that much information in the file name. There already is way more complexity in there as I ever wanted to have.

So what I want to do is provide a better replacement character when replacing "%u" so the filename sanitizer doesn't just kill all split characters in there.

A better solution to somehow save the full URL would be to actually add it to the metadata of the actual image file. A short web search revealed that there may be existing libraries that can be used to do this. But I have to check which one I can use without getting into licensing conflicts, first.

**Comment by M-Reimer** [comment]
New version with this change (better replacement characters) is on its way.

The part with the metadata editing will be added after this bug is fixed: https://github.com/M-Reimer/savescreenshot/issues/36

**Comment by cwfoo** [comment]
@M-Reimer Has this feature been implemented? I noticed that some additions were made in 9fcf8cd0 and 68059b30.

**Comment by M-Reimer** [comment]
It is and it is enabled by default. All you need is a tool which is able to read image comments.
