### ISSUE TITLE
Where are "Save Screenshot" settings stored?

### ISSUE THREAD

**Issue by tobwz** [M-Reimer/savescreenshot#31]
Recently I starting a system cleaning (outside of Firefox) for all my junk, temp, log and other stuff.

Accidentially I must have cleaned the settings of Save Screenshot AddOn too.

After launching Firefox all my previously AddOn options were reset to initial values and I had to re-adjust them.
The AddOn itself was still existing and enabled.

In order not to get this situation again I want to exclude the cleaning scope.

Where (in which folder) does "Save Screenshot" stored its settings?
Does it store something in user.prefs or other file?

Thank you
Tobias

**Comment by M-Reimer** [comment]
Maybe that's a good starting point:

https://discourse.mozilla.org/t/in-which-file-are-stored-an-add-on-settings-options/26064

Add-ons are limited to what Firefox allows them to access. There is an API which I use to tell Firefox "store this list of settings" and Firefox decides on its own where the contents are saved to.
