### ISSUE TITLE
Full page doesn't work when use AWS

### ISSUE THREAD

**Issue by caliburn1994** [M-Reimer/savescreenshot#32]
![Lambda](https://user-images.githubusercontent.com/11318894/117156334-86344800-adf8-11eb-99a2-258c785be719.png)

**Comment by caliburn1994** [comment]
It works when I use it to capture google search results.

**Comment by M-Reimer** [comment]
This page seems to scroll "internally". Means that it's not the <body> which is scrolling.

This is impossible to fix "globally" but would very well work with a "per service" workaround. Meaning that, if there is any need to regularly screenshot such pages, it would be possible to add a small CSS "fix" to my Add-on specially for this domain which is added before screenshotting and then removed afterwards.

So the question is: Is it worth it? Do you really need screenshots for this page?
And: Can I have access to a page like this without having to pay anything? Does Amazon offer a free trial or something?

**Comment by caliburn1994** [comment]
Yeah AWS has free time to try the service, and this is a "create" page, so nothing happens.  But you must input your credit card at first. (When all is done, you can delete the account)

**Comment by M-Reimer** [comment]
Sorry, but I won't be able to do this for "subscription only" websites. The only way, I can think for now, would be:

Hit "Ctrl + S" and do a full page save of the website. After doing so, please open this saved page and verify that the same screenshot problem exists there. It is your job to remove potentially private information from the saved HTML file. Then create a ZIP file from both, HTML and the folder with the additional files that belong to it and attach it here.

I'll also need a full URL of this page so I can match for it to apply a custom style for this special case.

**Comment by M-Reimer** [comment]
I have to close this one as I received no further feedback.

If someone else has this issue and wants to support me with solving this problem, please comment here so the issue can be reopened.
