### ISSUE TITLE
Full page doesn't work in GMail

### ISSUE THREAD

**Issue by hellsing71** [M-Reimer/savescreenshot#33]
When trying to make a screenshot of a Google Mail message longer than the viewport the app makes only a picture of the viewport. I tried Full page png, jpeg and copy. I have the latest Firefox (89.0) and savescreenshot (updated on May 1, 2021).

**Comment by M-Reimer** [comment]
Are you really sure that you want to screenshot e-mails? I think you should better print it to PDF instead.

If you really need screenshots from GMail, then the only possible way (if at all) is:
Use the Firefox "Save Page" feature and be sure to save the full page with all the corresponding files. This should end in a HTML file and a directory with additional files.

Now open the saved HTML file and verify that the screenshot issue still exists there. If so, it is now your responsibility to open the HTML file into the text editor of your choice and delete all private information.

After doing so: Create a ZIP file of both, the HTML and the subdirectory with additional files, and attach it here.

**Comment by M-Reimer** [comment]
A few minutes ago I did try to get GMail access on my own but they want me to enter a phone number which I, for sure, will not give to Google.

If printing to PDF is a good alternative for you, please close this issue.

If you still need screenshots of Google Mail messages, then please follow my above steps.

**Comment by M-Reimer** [comment]
I have to close this one as I received no further feedback.

If someone else has this issue and wants to support me with solving this problem, please comment here so the issue can be reopened.
