### ISSUE TITLE
Extension does not work anymore since Firefox 89

### ISSUE THREAD

**Issue by syldub69** [M-Reimer/savescreenshot#34]
Hi,
Since Firefox 89, the extension is not working.
The icon of Save Screenshot can still be added to the Firefox toolbar, but when we click on it, nothing happen.

**Comment by M-Reimer** [comment]
I'm on Firefox 89 and everything still works. Means: Can't reproduce your issue. What exactly are you doing?

**Comment by syldub69** [comment]
I had something stuck in my Firefox after upgrade... I restarted it and now I see it's ok... sorry for the inconvenience!
