### ISSUE TITLE
how to remove the annoying http(s) in the file name

### ISSUE THREAD

**Issue by f1-outsourcing** [M-Reimer/savescreenshot#35]
20210716-140606-httpsgithub.comM-Reimersavescreenshotissuesnew.png

1. What point is it even saving this http(s) in the file name.
2. Why not replace invalid characters with spaces or -, that is better than having nothing?

**Comment by M-Reimer** [comment]
The HTTPS is part of the URL. If you configure a filename pattern to include it, then you also get the HTTPS.

The part about a better replacement character is already covered in #30
