### ISSUE TITLE
 2 suggestions

### ISSUE THREAD

**Issue by tom-vb** [M-Reimer/savescreenshot#38]
Hi, congratulations for this extension! I love it.
I would like to do 2 suggestions to improve this tool 

1) be able to to add the name file format options as a frame at the top and of the saved screenshot
2) be able to define a save directory for each screenshot region: fullpage, viewport, selection

thanks for your attention
best regards

**Comment by M-Reimer** [comment]
about 1. What exactly do you mean with this? A copy of the filename as a text above the actual website? Why? You have the same information in your filename.

about 2. Impossible. I can not change the save directory. It is always the configured "Download" directory. Firefox does not allow Add-ons to save anywhere else for security reasons.

**Comment by tom-vb** [comment]
Hi, thank you for your fast response!
about 1) it's because when you review your screenshots it's more confortable to have this full information in the image with no limitations, for example de filename length and character limitations in the file name (Please see image example created with
 fireshot pro)

![screenshot_20210831_171435](https://user-images.githubusercontent.com/83949165/131530013-d894783c-ced8-413b-a31f-67c60a66cc44.png)

**Comment by M-Reimer** [comment]
This is actually quite tricky. I get the picture directly in binary form from Firefox. Then I would have to create a canvas object from that, somehow add the black box above (in the right size! Text may wrap!).

The even bigger problem is that, if you ever need this URL again, you have to type this into the address bar manually.

My plan is to embed the URL into the image metadata at some time in the future. This would allow to get this information back from the screenshot in "machine readable" form to just paste it into the address bar.
