### ISSUE TITLE
Suggestion: Add header in screenshot with additional information

### ISSUE THREAD

**Issue by user321321** [M-Reimer/savescreenshot#39]
Hello,

the addon is great, but sometimes I wish that there is a header with additional information in the screenshots.
In this could be included for example:

![grafik](https://user-images.githubusercontent.com/34860275/132743181-e812b56c-2df4-4330-8678-20348faa1bfb.png)

So even if the file name is changed, important information remains in the screenshots.

I am not a programmer for addons, but maybe this would be very easy to implement with javascript and canvas.
- https://stackoverflow.com/questions/16947494/how-to-add-text-in-a-picture-file-png-with-javascript/16947820#16947820
- https://stackoverflow.com/questions/10673122/how-to-save-canvas-as-an-image-with-canvas-todataurl/15685544#15685544

**Comment by M-Reimer** [comment]
I won't edit in images.

In the upcoming release such information will be saved to the metadata of the image files (Comment field) which allows to get such information in "digital form". This is especially useful for long URLs to easily revisit them without typing them into the address bar manually.

And once again (mentioned several times): DO NOT use screenshots to archive pages! PDF files are smaller and more useful and there are Add-ons on addons.mozilla.org which allow you to save to PDF!
