### ISSUE TITLE
Add Auto Save Feature

### ISSUE THREAD

**Issue by Andronomos** [M-Reimer/savescreenshot#4]
This addon would be perfect if it automatically saved to your selected download directory. Is it possible to add this option? It would make bulk operations much quicker.

**Comment by M-Reimer** [comment]
I did a few tries (I never used this, as I want to be asked for the download target every time as I directly do some organizing).

Firefox *always* asks for what to do with the file you want to download.
But there is a checkbox which makes Firefox remember your choice.
![screenshot](https://user-images.githubusercontent.com/3519517/32271190-08d26596-bef9-11e7-8962-d18aceeaf1e0.png)

Please check this checkbox and then give this another try.

**Comment by Andronomos** [comment]
I only want images created by this addon to auto save. Otherwise I'd have to reset that setting whenever I was not using your addon which is just as inconvenient.

I primarily use your addon (and others in the past) to capture lots of images from websites in quick succession. Organization comes later for me. I need something that can take the screenshot in one click, and auto save it with the page title as the file name so I can capture anywhere from 1 to 100+ images in less than a few minutes.

**Comment by M-Reimer** [comment]
I had a deeper look at the "downloads" API. It actually allows exactly what you need. I've added this as optional feature and published the new version. It should be available as version 2.1.0 soon. Please give this a try.

**Comment by Andronomos** [comment]
Thank you very much, it's working perfectly. Is there a way I can donate a few bucks to you?

**Comment by M-Reimer** [comment]
I usually don't take money for my open source projects. At least so far I don't have any ideas how I could spend this money in a way that my open source work profits from it.
But thanks anyway for offering.
