### ISSUE TITLE
Save screenshot NOT as Raster layer possible?

### ISSUE THREAD

**Issue by tobwz** [M-Reimer/savescreenshot#41]
As I found out the savescreenshot tool save the webpage screenshots as PNG with Raster Layer resp. with transparency.

This way I have later difficulties with image editors.

Is it possible to tell the AddOn NOT to save the PNG as Raster Layer but as "normal", flat, single layer *.png images?

**Comment by M-Reimer** [comment]
I guess you just use the wrong kind of image editor :stuck_out_tongue_closed_eyes: 

If I open the image in GIMP, then everything looks pretty normal. One layer as expected.

**Comment by M-Reimer** [comment]
I had a look at the API in Firefox and also at how the transparency is actually stored in PNG files.

- The API does not allow to change this in any way. I get what I get from Firefox.
- The alpha channel is encoded "per pixel" and then compressed with the whole image data. So there is no easy way to just "patch out" this value.

So nothing that I could influence easily and actually every image editor, which implements the PNG specification at a reasonable level, should have no problem with an alpha channel.
