### ISSUE TITLE
FR: Allow saving screenshots to a user-defined folder

### ISSUE THREAD

**Issue by Gitoffthelawn** [M-Reimer/savescreenshot#43]
Thank you for the wonderful extension.

I'm trying it out to see if I like it enough to switch from my favourite screenshot extension for Firefox (that I've used for years).

One of the feature the other extension has is the handy ability to specify the folder in which to automatically save the screenshots.

I'm not sure if you'll be limited to subfolders of the downloads folder, but even if so, that will still be a big improvement.

Thanks again!

**Comment by M-Reimer** [comment]
Should be possible, but I think I have to clean up the options page a bit, first.

And you are right that we will be limited to subdirectories of the "downloads" directory. This is a security feature. Add-ons can't access stuff anywhere they want.

**Comment by M-Reimer** [comment]
Fixed in 9.2.0

**Comment by Gitoffthelawn** [comment]
Thank you!
