### ISSUE TITLE
Some sites not working

### ISSUE THREAD

**Issue by linuxnewbee** [M-Reimer/savescreenshot#53]
Try this page:
https://www.verkkokauppa.com/fi/product/176513/Transcend-StoreJet-25H3P-2-Tt-USB-kovalevy
I cannot get a screenshot of this page and I could before so something has changed.
Any settings to tweak or...?
Thanks!

**Comment by linuxnewbee** [comment]
To clarify, viewport works, but not full page (jpg).

**Comment by M-Reimer** [comment]
Worked immediately for me. Do you get an error message?

**Comment by M-Reimer** [comment]
No feedback. Closing.

**Comment by linuxnewbee** [comment]
Yes, sorry,
my bad.

You were correct, I had some spider in my laptop and forgot to tell you.

Btw. I found a workaround for the "copy last" function on my wish list.
Open a new tab and minimize/center the window to your liking.
Then you just click viewport (png/jpg). Switch the embedded tab and 
click viewport again and so on.
Much quicker and easier than to use the Selection multiple times.

Your tool rocks ;-)
No need for anything else.

Best regards,
Bo


Manuel Reimer kirjoitti 26.4.2023 19:28:
