### ISSUE TITLE
gmail issue

### ISSUE THREAD

**Issue by hellsing71** [M-Reimer/savescreenshot#54]
I think this situation should be handled:

_Uncaught Error: Access to 'blob:https://mail.google.com/500fd229-78f1-4de1-9c56-a03d1ea6...' from script denied_

No full page, viewport or selection of gmail can be shot. Some visible message to the user would be great.

**Comment by M-Reimer** [comment]
I can not reproduce this problem. This is the usual problem if people report issues with websites you need a login for. I did try to create a dummy account but they want a phone number from me (which I won't give them!).

I did see a problem with creating a screenshot of a "blob:" page which could also fix your issue. Maybe you can temporarily install the current GIT version and report back:

https://github.com/M-Reimer/savescreenshot/commit/f7dd976cce1b4530e1f9a8b6337676a61f8d29dd

**Comment by M-Reimer** [comment]
No feedback. Closing.
