### ISSUE TITLE
No screenshots saved since Wednesday, July 26

### ISSUE THREAD

**Issue by firelinefiend** [M-Reimer/savescreenshot#59]
The add-on (which I **_love_**!) is still active, still set properly and acts as if it's working, but the last screenshot it saved was July 26th (it's set to save without asking for a save location). Went to check a saved screenshot from 2 days ago and there was nothing. Nothing in settings should have changed, everything still looks okay, and upon taking a screenshot, the "downloads" button still turns into a circle, then a checkmark in a circle, but there's nothing new in the downloads folder, not one screenshot.

There was a previous problem, not sure if it was on the same date, where everything worked properly and then there was no indicator anymore that files were being saved, because they weren't. That was resolved by closing the browser and restarting it. But this is a completely different problem, considering there have been many, many restarts of the browser (at least 10?) since July 26th. I normally take daily screenshots and then only consult with them when needed, and sometimes they're not needed until weeks or months later.

Technical info: Windows 10, Firefox 116.0.1 (64 bit), Save Screenshot should be latest version.

Thanks in advance.

**Comment by firelinefiend** [comment]
It's working, but strangely enough, after July 26th and no changes, it was moved to the documents folder, which isn't where it was supposed to be going! I discovered this after removing and re-adding.

Thank you for this add-on, It's great to have it "back" working, even though it's weird how it switched folders. Maybe it did that after the original problem where nothing was saved.

**Comment by M-Reimer** [comment]
Then you probably changed the "Downloads" directory in Firefox at some point.
My Add-on is limited by a sandbox. The only directory, it can write to, is the configured "Downloads" directory which can be changed in the Firefox settings.

**Comment by firelinefiend** [comment]
Thank you. I never changed it; it defaults to Documents now, which I try to keep as a "clean" folder, with no individual files. I'll have to find a better option, but SO happy not to have lost this add-on! It's been so invaluable. Screenshots can be saved without being prompted for a filename every time. Hands down this is the BEST add-on ever, because it's extremely useful. Thank you so much!
