### ISSUE TITLE
Allow to disable context menu generation

### ISSUE THREAD

**Issue by M-Reimer** [M-Reimer/savescreenshot#6]
Would be handy to be able to disable the context menu option for people who only need the toolbar button. Maybe even disable this by default, as with Firefox 57 it is easy to place the button to the "More tools..." menu.

**Comment by Defrilitus** [comment]
Thanks for considering this enhancement!

**Comment by M-Reimer** [comment]
Fixed in 2.2.0

**Comment by Defrilitus** [comment]
Thank you! Much appreciated.
