### ISSUE TITLE
Problem: Partially shifted/covered content for this webpage

### ISSUE THREAD

**Issue by pstein** [M-Reimer/savescreenshot#61]
In general Save Screenshot WebExt works fine here for my 64bit Firefox v116.0.3 under Win10.

But when I print the following full webpage some parts at in the middle are NOT printed into *.png.
It seems to my that the currently invisble part is shifted north

https://chrome.google.com/webstore/detail/visual-bookmarks/jdbgjlehkajddoapdgpdjmlpdalfnenf

Can you check it?

**Comment by pstein** [comment]
Hmm, here is what I get (see attached snapshot):

![snapshot](https://github.com/M-Reimer/savescreenshot/assets/2775875/66a0fb09-0cbe-4522-8a4b-7b082afbadfd)

**Comment by M-Reimer** [comment]
Exactly what I see. For me this looks like this website prepares stuff "out of view". Please try with the Firefox built in screenshot tool. If this brings the same result, then this one is a WONTFIX.

**Comment by M-Reimer** [comment]
If you have a bug ID, then please share it here.

**Comment by M-Reimer** [comment]
No more feedback. Closing.
