### ISSUE TITLE
[FR] Make metadata more easily accessible

### ISSUE THREAD

**Issue by claudio-salvio** [M-Reimer/savescreenshot#63]
Hello @M-Reimer 

First of all thanks for this useful extension. 🙏

I know that since some time ago is available the **option to save metadata as comment** and I have it enabled..
If I view the screenshots with a binary editor, I see that the metadata is there.

I mostly use **Windows** and I think it would be very useful to have that info stored so that it can be viewed using the **Details tab** in the file **Properties window**.

<img width="412" alt="Properties Windows, Details Tab, example, size=412x535" src="https://github.com/M-Reimer/savescreenshot/assets/66575834/df67e6ab-23b1-47e2-a2ed-3d33d7813ea5">  

​  
I also tried using a command line utility of **IrfanView** and I don't get it using that program either.
For the test I used a command like the following:
```powershell
. "C:\Program Files\IrfanView\i_view64.exe" "image.png" /info="image.png.txt" /fullinfo
```

Please make the necessary changes so that the metadata can be visualized using tools like these.

Best regards,
Claudio Salvio

**Comment by M-Reimer** [comment]
Sorry but no. I could provide info how to get it using ImageMagick.

**Comment by Gitoffthelawn** [comment]
Instructions for ImageMagick are welcome.  Also, if possible, ExifTool.

**Comment by M-Reimer** [comment]
Is on my TODO list. Actually easiest is via Gimp. That's what I had in mind.

**Comment by Gitoffthelawn** [comment]
Sounds good.  Although I do like Gimp, it's a beast to load, and I tend not to put it on pendrives because of it's size.  That's why I was thinking of Exiftool (fairly small) or ImageMagick (because you mentioned it, and it is reasonably fast).

**Comment by Gitoffthelawn** [comment]
Thanks.  Are these comments totally separate from Exif, IPTC, etc. metadata?

Does the answer depend on whether PNG or JPG format is used?

**Comment by M-Reimer** [comment]
Comments are specified in the image format specification. I don't know how other systems work.
