### ISSUE TITLE
long pages not work on pixel 8 pro

### ISSUE THREAD

**Issue by kanelau** [M-Reimer/savescreenshot#67]
Thank you first for providing such amazing tool. I installed it on my mi10 ultra, pixel 8 pro and my Chromebook. Both mi10 ultra and Chromebook work very well for full page screenshot. But if it is a long page, it doesn't work on pixel 8 pro, no response , short page is OK. Any clue to fix it?

**Comment by kanelau** [comment]
Sorry to add, sometimes mi10 ultra doesn't work either for long pages.

**Comment by M-Reimer** [comment]
Please provide an URL to test with.

**Comment by kanelau** [comment]
https://cn.wsj.com/amp/articles/%E5%8F%AA%E9%9D%A0%E7%A4%BE%E4%BF%9D%E9%87%91%E8%BF%87%E4%B8%8A%E7%9A%84%E7%BE%8E%E5%9B%BD%E9%80%80%E4%BC%91%E7%94%9F%E6%B4%BB-bb3f83f4

**Comment by M-Reimer** [comment]
So no valid example. Please check the URLs mentioned here if you can reproduce the issue:

https://github.com/M-Reimer/savescreenshot/issues/57

**Comment by kanelau** [comment]
please use the following link as an example to test. Thanks


https://edition.cnn.com/2024/02/15/politics/takeaways-fani-willis-testimony-georgia/index.html

**Comment by M-Reimer** [comment]
I was able to create a screenshot of this URL just fine with my phone (Pixel 6a).
But I had a bug which caused issue with some pages. Fix for this case will be part of the next release.

**Comment by kanelau** [comment]
Many thanks for your efforts. I look forward to your next release.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kanelau** [comment]
> I was able to create a screenshot of this URL just fine with my phone (Pixel 6a).
> But I had a bug which caused issue with some pages. Fix for this case will be part of the next release.

I guess this problem is caused by the page being too long and having too much content.  The situation I encountered was that it was impossible to take screenshots of extremely long pages.  For example, you cannot take a screenshot of this page https://cn.nytimes.com/health/20240315/deathbed-visions-research/

**Comment by M-Reimer** [comment]
I just found another bug while debugging this one. Taking screenshots on Desktop Firefox should be more stable with this upcoming fix.

BUT: Yes, I can reproduce the issue with your URL. And the line that causes an exception is the actual call into Firefox to get the image of the active tab. So the bug is inside of Firefox. My guess would be that we have some size limit again. I think I'll check for the max size at first by just adding a loop which decreases the screenshot height until the exception is gone and then I'll check to find out where this limit actually comes from.

But the actual fix would then be to reduce the limit for Android Firefox and create a bug report for Mozilla in parallel in hope this gets fixed or improved.

**Comment by M-Reimer** [comment]
I did a test and found that the maximum possible height on my phone is 12561 pixels. And it doesn't seem to depend on the page width. I tried two long pages and the highest height, I got success with, always was 12561 pixels. So I guess it's not the image area that limits here. But 12561 is also a bit random. I also could not find this number in the Mozilla source code anywhere...

**Comment by kanelau** [comment]
Many thanks for your update. Look forward to your next version.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by M-Reimer** [comment]
This was an issue with "high DPI" screens.
Your example page now is saved as screenshot successfully with my last change BUT you won't get the full page. There is a size limit defined by Firefox internally. Going above that will result in an exception.

**Comment by Gitoffthelawn** [comment]
> But 12561 is also a bit random. I also could not find this number in the Mozilla source code anywhere...

It's actually not random... you just need to think like the person who coded that undocumented limit.  They drank 3 shots of tequila every hour for 53 straight days and then they puked for the next 79 days.  3*53*79=12561.  See, it all makes perfect sense now.
