### ISSUE TITLE
add in the dropdown menu an option delay 10s 

### ISSUE THREAD

**Issue by f1-outsourcing** [M-Reimer/savescreenshot#68]
Maybe it is nice if there is a delay option in the drop down menu. If people activate it they have time to hover over something and then the screen capture is made. 
Tbh no idea if that even works with screen captures

**Comment by M-Reimer** [comment]
Please try if the keyboard shortcut feature works for you here.

**Comment by f1-outsourcing** [comment]
Sorry but I have been looking at these texts and settings in manage extension, but I don't see anything written about a short cut key. 
If you hardly use this delay it is also nicer to have this in the menu. I think short cut keys are best when you use them often.

**Comment by M-Reimer** [comment]
Please try this.
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
The menu is already complicated enough and if hovering with the mouse matters, the obvious choice is to not use the mouse to trigger the screenshot.

**Comment by f1-outsourcing** [comment]
> Please try this. https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox The menu is already complicated enough and if hovering with the mouse matters, the obvious choice is to not use the mouse to trigger the screenshot.

Did not even know it existed, thanks for this tip. I straight away removed the short cuts other plugins had set  ;)

**Comment by M-Reimer** [comment]
> Did not even know it existed, thanks for this tip. I straight away removed the short cuts other plugins had set ;)

Does not answer my question 😉
Does a shortcut work for your usecase for the "screenshot on hover" problem?
Adding something to the menu is not really an option as the menu is auto generated from your settings.

**Comment by f1-outsourcing** [comment]
short cut does indeed work :)

**Comment by M-Reimer** [comment]
Thanks for testing. I took the opportunity to add the link to the AMO Add-on description so people more likely find it to configure their shortcuts. I also added a note about the saved metadata and how to extract it.
