### ISSUE TITLE
No screenshot

### ISSUE THREAD

**Issue by Zorroblanco** [M-Reimer/savescreenshot#7]
Hi I cant take screenshot for this web https://www.taringa.net/  for example here https://www.taringa.net/J0RGTX/mi/Ubfmn  https://www.taringa.net/-Gyro-Zeppeli-/mi/Ub0m9?page=2  and still have this problem https://github.com/M-Reimer/savescreenshot/issues/5 no take screenshot from https://marcjapan.wordpress.com/2010/08/08/recopilatorio-curso-de-japones/ Cheers and thanks in advance (sorry for my english) Firefox 59.0.2 (32bit) win 7 ultimate (x86)

**Comment by M-Reimer** [comment]
> Hi I cant take screenshot for this web https://www.taringa.net/ 

Works for me. Same Firefox version here, but Linux as OS. I've tried several times without any problems. Do you see errors in "Broser console" (Menu -> Web Developer -> Browser Console)

> no take screenshot from https://marcjapan.wordpress.com/2010/08/08/recopilatorio-curso-de-japones/ 

Works for me, too. Again, I'm able to take a screenshot, but it is limited in size and it takes pretty long (maybe because this pretty big image takes some time to be compressed).

**Comment by Zorroblanco** [comment]
Thanks for your answer and your time! I reinstall Firefox and now it s working, but if I change option to Display "Save as" dialog no take screenshot large (no problem with offer to open the image file directly)

**Comment by THX-11-38** [comment]
Auf den Seiten http://www.dtac.co.th/en/ funktioniert die Screenshot-Funktion Meldungslos nicht.

**Comment by M-Reimer** [comment]
Bitte erneut mit Firefox 61 testen. Ich konnte das Problem letztens noch nachvollziehen, bei mir ist es aber mit dem Browser-Update verschwunden.

**Comment by THX-11-38** [comment]
Auch mit der FF 61.0-64bit klappt es unter W7U64bit nicht.

**Comment by M-Reimer** [comment]
Sollte gefixt sein. Die Ursache war der "|" im Dateinamen.

Wenn es weitere solche Seiten gibt, dann entweder wieder aufmachen oder einen separaten Bug dafür öffnen.

**Comment by THX-11-38** [comment]
Hallo Manuel.
Perfekt! Vielen Dank für den Fix und natrlich auch für das AddOn!
MfG
Stefan Müller
