### ISSUE TITLE
Align the text to left inside of popup

### ISSUE THREAD

**Issue by kallookoo** [M-Reimer/savescreenshot#9]
Hi,
Is possible align the text inside of popup after press de camera icon.
Personally I think it does not look good, in my language.

See screenschot:
<img src="https://i.imgur.com/llpvdWg.png" />

Thanks

**Comment by M-Reimer** [comment]
Exactly. This popup is meant to look like regular menus and so the text should be left-aligned.

**Comment by M-Reimer** [comment]
Final modification is now in 3.2.0.
I did several screenshots and compared my menu to the "original" Firefox menu over and over again. I think now I'm pretty close.
